### PR TITLE
Moder Phobos compilation fix

### PR DESCRIPTION
**Pull request by denizzzka**

### CODE REVIEW

**Comment by free-beer** [comment]
Hey, talk about timing! I just started taking a look at this again yesterday to re-structure it in the fashion dub normally uses and to add unit tests. I'll see if I can get that change finished out in the next few days.

**Comment by free-beer** [comment]
Okay, changes pushed into place. Let me know if this is causing you any issues.

**Comment by denizzzka** [comment]
This PR can be closed?

**Comment by free-beer** [comment]
@denizzzka  if you're happy with whats there now then it can be.

**Pull request closed without merging**
